"""empty message

Revision ID: 5c58d2c1ee43
Revises: 5c2ba8664252
Create Date: 2022-05-22 17:57:10.403138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c58d2c1ee43'
down_revision = '5c2ba8664252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos1', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos1', 'completed')
    # ### end Alembic commands ###
